os:
  - linux
  - osx

language: cpp

dist: bionic

osx_image: xcode12.2

compiler:
  - clang
  - g++

addons:
  apt:
    packages: 
      - valgrind
    update: true

install:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1 -j
 
script:
  - make test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -v ./examples/arg ;
    fi