os:
  - linux
  - osx

language: cpp

dist: bionic

osx_image: xcode12.2

addons:
  apt:
    packages: 
      - valgrind
  homebrew:
    packages:
      - valgrind
    update: true

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - gcc-7
#       - g++-7
#       - cmake
install:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make VERBOSE=1 -j
 
script:
  - make test
  - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -v ./examples/arg